### ISSUE TITLE
Google Drive is sometimes not syncing renames

### ISSUE THREAD

**Issue by lukechurch** [AfricasVoices/CoreDataModules#66]
At the moment I have a circumstance where drive is not syncing a rename applied to a file from one of the RO's computers. It is renamed correctly online, but not in my local copy.

This means that the pipeline does not pickup the files correctly.

**Comment by lukechurch** [comment]
We're not using Drive Sync anymore

**Comment by as2388** [comment]
That's not true - I need to be able to update the analysis dataset files in Drive after every pipeline run

**Comment by as2388** [comment]
Although the names of those don't change...

**Comment by as2388** [comment]
Now it's true that we're not using Drive sync anymore. Closing.
